spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot?characterEncoding=utf-8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
        instance-id: ${spring.application.name}:${server.port}
        health-check-interval: 10s
        health-check-path: /actuator/health
        tags: dev
        register: true
        register-health-check: true
        prefer-ip-address: true
      port: 8500
      host: 121.36.54.71
  application:
    name: iot-platform
  #    bootstrap-servers：连接kafka的地址，多个地址用逗号分隔
  #    batch-size：当将多个记录被发送到同一个分区时， Producer 将尝试将记录组合到更少的请求中。这有助于提升客户端和服务器端的性能。这个配置控制一个批次的默认大小（以字节为单位）。16384是缺省的配置
  #    retries：若设置大于0的值，客户端会将发送失败的记录重新发送
  #    buffer-memory：Producer 用来缓冲等待被发送到服务器的记录的总字节数，33554432是缺省配置
  #    key-serializer：关键字的序列化类
  #    value-serializer：值的序列化类
  kafka:
    listener:
      missing-topics-fatal: false
    bootstrap-servers: 121.36.54.71:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.cqmike.asset.kafka.PEncodeKafka
      properties:
        linger.ms: 1
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.cqmike.asset.kafka.PDecodeKafka
      properties:
        session.timeout.ms: 15000
      group-id: kafkaTopic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL55Dialect
  jackson:
    serialization:
      indent-output: true
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 0
#    password: cqmike
    feign-token: 072C08C21F8E8B0AD2CB83FDF9EADBE0
server:
  port: 8088
swagger:
  markdowns: classpath:markdown/*
  basic:
    enable: true
    username: root
    password: 123456
