mock:
  netty:
    server:
      host: localhost
      port: 8888
      count: 10
spring:
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${server.port}
        health-check-interval: 10s
        tags: dev
        register: false
        register-health-check: true
        heartbeat:
          enabled: true
      port: 8500
      host: 121.36.54.71
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 0
#    password: root
  application:
    name: iot-mock
server:
  port: 8083
mqtt:
  host: tcp://121.36.54.71:1883
  client-id: ${spring.application.name}:${server.port}
  default-sender-topic: mock
  username: root
  password: cqmike

feign:
  platform:
    name: iot-platform
    url: localhost:8088